export type IndustryOption = { name: string; count: number };

export const UNCLASSIFIED_INDUSTRY_LABEL = '未分类';

export const INDUSTRY_PINYIN_ABBR: Record<string, string> = {
  半导体: 'bdt',
  白酒: 'bj',
  白色家电: 'bsjd',
  保险: 'bx',
  包装印刷: 'bzys',
  厨卫电器: 'cwdq',
  电池: 'dc',
  电机: 'dj',
  电力: 'dl',
  电网设备: 'dwsb',
  多元金融: 'dyjr',
  电子化学品: 'dzhxp',
  房地产: 'fdc',
  风电设备: 'fdsb',
  非金属材料: 'fjscl',
  服装家纺: 'fzjf',
  纺织制造: 'fzzz',
  工程机械: 'gcjx',
  光伏设备: 'gfsb',
  贵金属: 'gjs',
  轨交设备: 'gjsb',
  港口航运: 'gkhy',
  公路铁路运输: 'gltlys',
  钢铁: 'gt',
  光学光电子: 'gxgdz',
  工业金属: 'gyjs',
  环保设备: 'hbsb',
  环境治理: 'hjzl',
  互联网电商: 'hlwds',
  黑色家电: 'hsjd',
  化学纤维: 'hxxw',
  化学原料: 'hxyl',
  化学制品: 'hxzp',
  化学制药: 'hxzy',
  IT服务: 'itfw',
  机场航运: 'jchy',
  军工电子: 'jgdz',
  军工装备: 'jgzb',
  家居用品: 'jjyp',
  计算机设备: 'jsjsb',
  金属新材料: 'jsxcl',
  教育: 'jy',
  建筑材料: 'jzcl',
  建筑装饰: 'jzzs',
  零售: 'ls',
  旅游及酒店: 'lyjjd',
  美容护理: 'mrhl',
  煤炭开采加工: 'mtkcjg',
  贸易: 'my',
  农产品加工: 'ncpjg',
  农化制品: 'nhzp',
  能源金属: 'nyjs',
  汽车服务及其他: 'qcfwjqt',
  汽车零部件: 'qclbj',
  汽车整车: 'qczc',
  其他电源设备: 'qtdysb',
  其他电子: 'qtdz',
  其他社会服务: 'qtshfw',
  软件开发: 'rjkf',
  燃气: 'rq',
  塑料制品: 'slzp',
  食品加工制造: 'spjgzz',
  生物制品: 'swzp',
  石油加工贸易: 'syjgmy',
  通信服务: 'txfw',
  通信设备: 'txsb',
  通用设备: 'tysb',
  文化传媒: 'whcm',
  物流: 'wl',
  消费电子: 'xfdz',
  小家电: 'xjd',
  小金属: 'xjs',
  橡胶制品: 'xjzp',
  元件: 'yj',
  医疗服务: 'ylfw',
  医疗器械: 'ylqx',
  饮料制造: 'ylzz',
  油气开采及服务: 'yqkcyfw',
  影视院线: 'ysyx',
  游戏: 'yx',
  银行: 'yh',
  医药商业: 'yysy',
  养殖业: 'yzy',
  自动化设备: 'zdhsb',
  综合: 'zh',
  证券: 'zq',
  中药: 'zy',
  专用设备: 'zysb',
  造纸: 'zz',
  种植业与林业: 'zzyyly',
  [UNCLASSIFIED_INDUSTRY_LABEL]: 'wfl',
};

export function normalizeIndustryQuery(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, '');
}

export function matchesIndustryQuery(option: IndustryOption, query: string): boolean {
  if (!query) {
    return true;
  }

  const name = normalizeIndustryQuery(option.name);
  const pinyinAbbr = INDUSTRY_PINYIN_ABBR[option.name]?.toLowerCase() ?? '';
  return name.includes(query) || pinyinAbbr.includes(query);
}
